- cmd/main.go
- data/nullify.yaml
- pkg/models/config.go
- pkg/validator/emails.go
- pkg/validator/emails_test.go
- pkg/validator/validate.go
Add email validator for secrets push workflow
[- (issue)](https://github.com/Nullify-Platform/Rebel-Base/issues/90)
> Add email validator

- .github/workflows/ci-go.yml
- .github/workflows/ci-require-labels.yml
- .github/workflows/release.yml
- renovate.json
Make renovate publish 1 pull request per week with all updates and automatically publish releases with the appropriate version upgrade.
- resolves https://github.com/Nullify-Platform/config-file-parser/issues/15
> renovate improvements and auto-release pipeline

- pkg/parser/defaults.go
Please include a summary of the change with relevant motivation and context
> adding high

- pkg/models/config.go
- pkg/parser/defaults.go
- pkg/parser/parse_test.go
- pkg/validator/glob.go
- pkg/validator/glob_test.go
Rename ignore_patterns to ignore_paths.
ignore_patterns sounds like regex.
> replace ignore_patterns with ignore_paths

- .github/workflows/ci-go.yml
> Remove codecov

- .github/workflows/ci-go.yml
- Makefile
CI is failing.
This change also makes it consistent with other services
> fix ci failing

- data/nullify.yaml
- pkg/models/config.go
- pkg/models/dependencies.go
- pkg/models/notifications_events.go
- pkg/models/notifications_targets.go
- pkg/models/scheduled_notifications.go
- pkg/parser/parse.go
- pkg/validator/notifications.go
- pkg/validator/notifications_test.go
- tests/integration_test.go
- tests/nullify.yaml
I'd like to get anyone's input on these or any others we should add
potential new config file options for:
- allowlisting CVEs
- configuring scheduled digest messages
> potential new config file options

- pkg/parser/defaults.go
add default maps in default config.
> add default maps

- pkg/parser/defaults.go
- tests/integration_test.go
- tests/nullify.yaml
Please include a summary of the change with relevant motivation and context
- relates to <insert-pr-link>
> Update NewDefaultConfig() to include all parameters in config file

- pkg/merger/merger.go
- pkg/merger/merger_test.go
- pkg/models/models.go
- pkg/parser/defaults.go
- pkg/parser/parse.go
- pkg/validator/severity_test.go
Add a function to merge both global and repo config files.
> add config file merge function for global and local config files

- examples/nullify.yaml
- pkg/merger/merger_test.go
- pkg/models/code.go
- pkg/models/dependencies.go
- pkg/models/secrets.go
- pkg/parser/parse_test.go
- tests/empty_fail_build.yaml
- tests/integration_test.go
- tests/nullify.yaml
- remove secrets whitelist
- make cve ignore filter a list
- organize the structs better
> remove secrets whitelist, make cve filters a list and organise the structs

- pkg/merger/merger.go
- pkg/merger/merger_test.go
- pkg/models/code.go
- pkg/models/dependencies.go
- pkg/validator/autofix.go
- pkg/validator/autofix_test.go
add the new auto-fix settings to the config file merge function
> merge the auto-fix settings

- pkg/models/code.go
- pkg/models/dependencies.go
change the yaml key from autofix to auto_fix to be the same as the example
> change auto-fix yaml key

- pkg/models/priority.go
Please include a summary of the change with relevant motivation and context
- relates to <insert-pr-link>
> feat: add priority ratings

- pkg/merger/merger.go
- pkg/merger/merger_test.go
- pkg/models/models.go
- pkg/models/secrets.go
- tests/integration_test.go
- tests/nullify.yaml
add custom secret pattern configuration options
> add custom secret patterns

- pkg/models/autofix.go
- pkg/models/models.go
Add some extra auto-fix options.
- labels: labels to apply to auto-fix pull requests
- global auto-fix config for all features
> add extra auto-fix options

- pkg/models/code.go
- pkg/models/dependencies.go
- pkg/models/secrets.go
> Add fail builds per feature

- pkg/models/attack_surface.go
- pkg/models/models.go
add options for the MVP attack surface scan
> add attack surface scan options

- pkg/models/severity.go
- pkg/models/severity_test.go
allow severity comparisons like `if CompareSeverity(cve.Severity, configmodels.HighSeverity) >= 0`
- covered by unit tests
- relates to <insert-pr-link>
> feat(AGI-162): compare severities quantitatively

- pkg/models/attack_surface.go
Add a customer facing feature flag to enable scheduled attack surface scans.
> add flag to enable attack surface monitoring

- examples/nullify.yaml
- pkg/merger/merger_test.go
- pkg/models/attack_surface.go
- tests/integration_test.go
- tests/nullify.yaml
Rename enable_dns_traversal to enable_dns_enumeration
> Rename enable_dns_traversal to enable_dns_enumeration
