Nullify-Platform/config-file-parser

Makefile, data/nullify.yaml, go.mod, go.sum, pkg/models/config.go, pkg/models/severity.go, pkg/parser/parse_test.go, pkg/parser/validate.go
Add minimum_comment_severity option which users can set to change the vulnerability severity which triggers nullify to leave a pull request comment.
- https://github.com/Nullify-Platform/The-Force/issues/576
=> add minimum_comment_severity option

pkg/models/severity.go, pkg/parser/defaults.go, pkg/parser/parse.go, pkg/parser/parse_test.go, pkg/validator/severity.go, pkg/validator/severity_test.go
Created a public function to return the default values if the user doesn't set them.
The ParseConfiguration function also uses this to set default values in parsed config files.
- https://github.com/Nullify-Platform/The-Force/issues/576
=> add default values

data/nullify.yaml, pkg/models/config.go, pkg/parser/defaults.go, pkg/parser/parse.go, pkg/parser/parse_test.go, pkg/validator/emails_test.go, pkg/validator/severity.go, pkg/validator/severity_test.go, pkg/validator/validate.go
Changes minimum_comment_severity to severity_threshold so that the config file option is inclusive of issue dashboards.
- https://github.com/Nullify-Platform/Rebel-Alliance/issues/127
=> update minimum_comment_severity to severity_threshold

data/nullify.yaml, go.mod, go.sum, pkg/models/config.go, pkg/parser/defaults.go, pkg/parser/parse_test.go, pkg/validator/glob.go, pkg/validator/glob_test.go, pkg/validator/validate.go
Added code to enable pattern matching using the ignore_patterns yaml tag. This will be used for detecting glob patterns in the-force and other services. 
=> added ignore patterns and added tests for glob patterns

pkg/models/config.go, pkg/parser/parse_test.go, pkg/validator/whitelist_secrets.go
Allowlist is a better term to use.
We should remove whitelist from the docs and deprecate it when everyone stops using it.
=> use allowlist instead of whitelist

data/nullify.yaml, pkg/models/config.go, pkg/models/secrets.go, pkg/parser/parse_test.go, pkg/validator/whitelist_secrets.go, tests/integration_test.go, tests/nullify.yaml
All features have their own config file block so we should be consistent.
the old secrets_whitelist field is still there which we will deprecate at some point.
setting this as a minor because we never released secrets_allowlist.
=> move allowlist to secrets block

data/nullify.yaml, pkg/models/code.go, pkg/models/dependencies.go, pkg/models/models.go, tests/integration_test.go, tests/nullify.yaml
Ignore CWEs and/or rule IDs with a reason and only applying to matching directories or path patterns.
=> add ability to ignore cwe's and rule ids for code/sast

cmd/main.go, examples/nullify.yaml, pkg/models/code.go, pkg/models/dependencies.go, pkg/models/notifications.go, pkg/models/scheduled_notifications.go, pkg/models/secrets.go, tests/integration_test.go, tests/nullify.yaml
In the global config file e.g. .github-private repository, we want to have settings applicable to a subset of the repositories.
=> add global only repository list for all relevant settings

pkg/merger/merger.go
Include secrets whitelist in config file merge.
we will deprecate it later once we can detect all customers are migrated.
=> include secrets whitelist in merge

examples/nullify.yaml, pkg/models/autofix.go, pkg/models/models.go, pkg/validator/autofix.go, pkg/validator/autofix_test.go, pkg/validator/notifications_test.go
after a 2nd look at it, i think having a consistent `max_pull_request` prefix for both auto-fix pull request creation limits is better.
Also change `period` to `days` because time.ParseDuration only does units up to hours and our most common unit will probably be days, if not weeks.
=> use consistent max_pull_request prefix for the 2 auto-fix pr creation limits

examples/nullify.yaml, pkg/models/secrets.go
* add sha256 matcher for secrets, to support allowlisting from dashboard/API/sources where we don't have the underlying value
- relates to <insert-pr-link>
=> feat(NUL-649): add the sha256 matcher for secrets allowlisting

pkg/merger/merger.go, pkg/merger/merger_test.go
Refactor the MergeConfigFiles function to take in a list of config files.
This is in preparation for providing an extended hierarchy of config files:
- system default
- dashboard settings
- .github-private
- repo
=> merge list of config files

examples/nullify.yaml, pkg/merger/merger.go, pkg/merger/merger_test.go, pkg/models/code.go, pkg/models/dependencies.go, pkg/models/models.go, pkg/models/secrets.go, pkg/parser/defaults.go, pkg/validator/severity.go, tests/integration_test.go, tests/nullify.yaml
add feature flags for pull request reviews and issue dashboards.
this will allow the customer to control these feature flags themselves.
=> add feature flags

pkg/merger/merger.go, pkg/merger/merger_test.go
If there is a global config file and repo config file, the repo config file is not overriding the global Jira settings. Only priorities and assignees were being overridden.
the fix allows project key, issue type etc to also be overriden if they are not empty strings
=> fix jira override behaviour

examples/nullify.yaml, pkg/merger/merger.go, pkg/merger/merger_test.go, pkg/models/integrations.go, tests/integration_test.go, tests/nullify.yaml
the user should be able to specify the priority threshold and Jira tickets are only created for those findings above the specified priority
=> add priority threshold to jira

pkg/validator/severity.go, pkg/validator/severity_test.go
there is a bug where the empty string and other valid config files are coming up as invalid. this behaviour is also inconsistent with the comment
`isValid := validator.ValidateConfig(parsedConfig)` returns false
=> fix: add empty string to valid severities

examples/nullify.yaml, pkg/merger/merger.go, pkg/merger/merger_test.go, pkg/models/attack_surface.go, pkg/models/models.go, tests/integration_test.go, tests/nullify.yaml
add some tests and cleanup attack surface monitoring config file options.
ended up fixing a bug in the merge function.
=> add tests for attack surface monitoring

examples/nullify.yaml, pkg/merger/merger_test.go, pkg/models/attack_surface.go, tests/integration_test.go, tests/nullify.yaml
Modify include and ignore rules so that:
* IP address and Domain Names are consolidated into a single Hosts field
* Added Method to include rules
=> Modify include and ignore rules

pkg/models/attack_surface.go, tests/integration_test.go, tests/nullify.yaml
get the rolename from the config which will be used to assume across customer accounts
=> add roleName to the config file parser

examples/nullify.yaml, pkg/merger/merger_test.go, pkg/models/attack_surface.go, tests/integration_test.go, tests/nullify.yaml
Match parity betewen include and ignore rules (i.e. add transportProtocols and ports to include rules)
=> Attack surface monitoring: parity between includeOnly and ignore

pkg/merger/merger_test.go, pkg/models/priority.go, pkg/parser/defaults.go, pkg/parser/parse.go, pkg/validator/severity.go, tests/integration_test.go, tests/nullify.yaml
* add case insensitivity for priority threshold, update to the 3 labels available in our agents
* I've marked this as major because the label change is technically a breaking change - can adjust based on comments
* the old labels aren't explicitly used anywhere in code
* customers _may_ already have the old labels in their config files though - I may need to update this PR to account for that
* though - https://docs.nullify.ai/getting-started/configuration-general `priorityThreshold` is not yet documented so we can still change it at will and have it technically not be a breaking change :sweat_smile: 
=> feat(ENT-923): update priority threshold in config file parser

pkg/models/priority.go, pkg/models/priority_test.go
* for priority threshold filtering in services
* e.g. used here https://github.com/Nullify-Platform/The-Force-SAST/pull/2286/files
=> chore(ENT-923): add priority comparison methods

pkg/models/priority.go, pkg/models/priority_test.go
* add unknown priority to have the option for customers to opt into all findings regardless of priority
* also needed to fix all the breaking integration tests when introducing priority threshold filtering
=> chore - add missing unknown priority

pkg/models/priority.go, pkg/models/priority_test.go
* short term backwards compatibility to prevent forced updates to hyperdrive in services that may not be ready to yet, if their config file parser versions have the breaking changes (removing the old priority levels)
=> chore - keep old priorities for temporary backwards compatibility
